name: 'fireblocks-sandbox-deploy'

services:
  gateway:
    build:
      context: .
      dockerfile: deploy.dockerfile
    ports:
      - 3344:3000
    environment:
      - APP=gateway
    networks:
      - internal
  provider:
    build:
      context: .
      dockerfile: deploy.dockerfile
    ports:
      - 4000:4000
    environment:
      - APP=provider
    networks:
      - internal
  schedule:
    build:
      context: .
      dockerfile: deploy.dockerfile
    ports:
      - 5000:5000
    environment:
      - APP=schedule
    networks:
      - internal
networks:
  internal:
    name: fireblocks-sandbox-internal
    external: true
